CREATE DATABASE IF NOT EXISTS workshopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON workshopdb.* TO 'workshop'@'localhost';
FLUSH PRIVILEGES;

USE workshopdb;

CREATE TABLE IF NOT EXISTS people (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  age INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
